// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNLZ5eTqq18Ml6Wbb5BTaC2eos-UJZ_Vs',
    appId: '1:453535154350:web:844d5d613818e19e82ad3f',
    messagingSenderId: '453535154350',
    projectId: 'listinglens-paas',
    authDomain: 'listinglens-paas.firebaseapp.com',
    storageBucket: 'listinglens-paas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE2lHtXcT-11dy94ILmUxJHNvO4rH9eyE',
    appId: '1:453535154350:android:a2a07ccc0cdbd97e82ad3f',
    messagingSenderId: '453535154350',
    projectId: 'listinglens-paas',
    storageBucket: 'listinglens-paas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI4y_GN7LmjulpPOkPLIdVZ3fFTpTN2R4',
    appId: '1:453535154350:ios:448c139932d99c7382ad3f',
    messagingSenderId: '453535154350',
    projectId: 'listinglens-paas',
    storageBucket: 'listinglens-paas.firebasestorage.app',
    iosBundleId: 'com.example.listingLensPaas',
  );
}
